#define _POSIX_C_SOURCE 200809L

#include "git.h"
#include "log.h"

#include <dirent.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

static hs_exec_result git_exec(const hs_git *g, const hs_strvec *args) {
    hs_strvec full;
    hs_vec_init(&full);
    hs_vec_push(&full, strdup("git"));
    for (size_t i = 0; i < args->len; i++)
        hs_vec_push(&full, strdup(args->data[i]));
    hs_exec_result r = hs_exec_args_dir(&full, g->repo_path);
    hs_strvec_free(&full);
    return r;
}

static int mkdirs(const char *path) {
    if (!path || !path[0]) return -1;
    char *tmp = strdup(path);
    size_t len = strlen(tmp);
    if (len > 1 && tmp[len - 1] == '/') tmp[len - 1] = '\0';

    for (char *p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = '\0';
            if (mkdir(tmp, 0755) != 0 && errno != EEXIST) {
                free(tmp);
                return -1;
            }
            *p = '/';
        }
    }
    int ret = (mkdir(tmp, 0755) != 0 && errno != EEXIST) ? -1 : 0;
    free(tmp);
    return ret;
}

static char *dir_of(const char *path) {
    char *dup = strdup(path);
    char *slash = strrchr(dup, '/');
    if (slash) {
        *slash = '\0';
    } else {
        free(dup);
        return strdup(".");
    }
    return dup;
}

static int copy_file(const char *src, const char *dst) {
    FILE *in = fopen(src, "rb");
    if (!in) return -1;
    FILE *out = fopen(dst, "wb");
    if (!out) { fclose(in); return -1; }

    char buf[8192];
    size_t n;
    int ok = 0;
    while ((n = fread(buf, 1, sizeof(buf), in)) > 0) {
        if (fwrite(buf, 1, n, out) != n) { ok = -1; break; }
    }
    if (ferror(in)) ok = -1;
    fclose(in);
    fclose(out);

    if (ok == 0) {
        struct stat st;
        if (stat(src, &st) == 0)
            chmod(dst, st.st_mode);
    }
    return ok;
}

static void copy_tree(const char *src, const char *dst);

static void copy_dir_recursive(const char *src, const char *dst) {
    mkdirs(dst);
    DIR *d = opendir(src);
    if (!d) return;
    struct dirent *ent;
    while ((ent = readdir(d)) != NULL) {
        if (strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
            continue;
        char *s = hs_join_path(src, ent->d_name);
        char *dd = hs_join_path(dst, ent->d_name);
        copy_tree(s, dd);
        free(s);
        free(dd);
    }
    closedir(d);
}

static void copy_tree(const char *src, const char *dst) {
    struct stat st;
    if (stat(src, &st) != 0) return;

    if (S_ISDIR(st.st_mode)) {
        copy_dir_recursive(src, dst);
    } else if (S_ISREG(st.st_mode)) {
        char *parent = dir_of(dst);
        mkdirs(parent);
        free(parent);
        if (copy_file(src, dst) != 0)
            hs_error("failed to copy %s -> %s", src, dst);
    }
}

static char *relative_path(const char *path, const char *base) {
    size_t blen = strlen(base);
    if (strncmp(path, base, blen) != 0) return strdup(path);
    const char *rest = path + blen;
    if (*rest == '/') rest++;
    return strdup(rest);
}

static int str_compare(const void *a, const void *b) {
    return strcmp(*(const char **)a, *(const char **)b);
}

static void strvec_insert_sorted_unique(hs_strvec *v, const char *s) {
    for (size_t i = 0; i < v->len; i++) {
        int cmp = strcmp(v->data[i], s);
        if (cmp == 0) return;
    }
    hs_vec_push(v, strdup(s));
}

static void update_gitignore(const hs_git *g, const hs_groupvec *groups) {
    hs_strvec excludes;
    hs_vec_init(&excludes);

    strvec_insert_sorted_unique(&excludes, ".ssh/");
    strvec_insert_sorted_unique(&excludes, ".gnupg/");
    strvec_insert_sorted_unique(&excludes, "*secret*");
    strvec_insert_sorted_unique(&excludes, "*token*");
    strvec_insert_sorted_unique(&excludes, "*.key");
    strvec_insert_sorted_unique(&excludes, "*.pem");

    for (size_t i = 0; i < groups->len; i++) {
        const hs_sync_group *grp = &groups->data[i];
        for (size_t j = 0; j < grp->exclude.len; j++)
            strvec_insert_sorted_unique(&excludes, grp->exclude.data[j]);
    }

    qsort(excludes.data, excludes.len, sizeof(char *), str_compare);

    char *gitignore_path = hs_join_path(g->repo_path, ".gitignore");
    FILE *f = fopen(gitignore_path, "w");
    if (f) {
        fprintf(f, "# Generated by hyprsync\n");
        for (size_t i = 0; i < excludes.len; i++)
            fprintf(f, "%s\n", excludes.data[i]);
        fclose(f);
    }
    free(gitignore_path);
    hs_strvec_free(&excludes);
}

static void copy_to_repo(const hs_git *g, const char *source) {
    char *repo_rel = hs_git_to_repo_path(g, source);
    char *dest = hs_join_path(g->repo_path, repo_rel);

    if (hs_dir_exists(source)) {
        copy_dir_recursive(source, dest);
    } else if (hs_file_exists(source)) {
        char *parent = dir_of(dest);
        mkdirs(parent);
        free(parent);
        if (copy_file(source, dest) != 0)
            hs_error("failed to copy %s -> %s", source, dest);
    }

    free(repo_rel);
    free(dest);
}

static void copy_from_repo(const hs_git *g, const char *repo_file) {
    char *rel = relative_path(repo_file, g->repo_path);
    char *dest = hs_git_to_original_path(g, rel);

    if (hs_dir_exists(repo_file)) {
        copy_dir_recursive(repo_file, dest);
    } else if (hs_file_exists(repo_file)) {
        char *parent = dir_of(dest);
        mkdirs(parent);
        free(parent);
        if (copy_file(repo_file, dest) != 0)
            hs_error("failed to copy %s -> %s", repo_file, dest);
    }

    free(rel);
    free(dest);
}

hs_git *hs_git_create(const hs_git_config *config, const char *hostname) {
    hs_git *g = calloc(1, sizeof(hs_git));
    if (!g) return NULL;

    g->config.repo = hs_strdup_safe(config->repo);
    g->config.auto_commit = config->auto_commit;
    g->config.commit_template = hs_strdup_safe(config->commit_template);

    g->hostname = hs_strdup_safe(hostname);
    g->repo_path = hs_expand_path(config->repo);
    g->home_dir = hs_get_home_dir();

    return g;
}

void hs_git_free(hs_git *g) {
    if (!g) return;
    free(g->config.repo);
    free(g->config.commit_template);
    free(g->hostname);
    free(g->repo_path);
    free(g->home_dir);
    free(g);
}

int hs_git_init_repo(hs_git *g) {
    if (hs_git_is_initialized(g)) {
        hs_debug("git repo already initialized at %s", g->repo_path);
        return 1;
    }

    mkdirs(g->repo_path);
    if (!hs_dir_exists(g->repo_path)) {
        hs_error("failed to create repo directory: %s", g->repo_path);
        return 0;
    }

    chmod(g->repo_path, 0700);

    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("init"));
    hs_exec_result result = git_exec(g, &args);
    hs_strvec_free(&args);

    if (!hs_exec_success(&result)) {
        hs_error("git init failed: %s", result.stderr_output);
        hs_exec_result_free(&result);
        return 0;
    }
    hs_exec_result_free(&result);

    hs_vec_init(&args);
    hs_vec_push(&args, strdup("config"));
    hs_vec_push(&args, strdup("user.name"));
    hs_vec_push(&args, strdup("hyprsync"));
    result = git_exec(g, &args);
    hs_strvec_free(&args);
    if (!hs_exec_success(&result))
        hs_warn("failed to set git user.name");
    hs_exec_result_free(&result);

    hs_vec_init(&args);
    hs_vec_push(&args, strdup("config"));
    hs_vec_push(&args, strdup("user.email"));
    hs_vec_push(&args, strdup("hyprsync@localhost"));
    result = git_exec(g, &args);
    hs_strvec_free(&args);
    if (!hs_exec_success(&result))
        hs_warn("failed to set git user.email");
    hs_exec_result_free(&result);

    hs_info("initialized git repo at %s", g->repo_path);
    return 1;
}

int hs_git_is_initialized(const hs_git *g) {
    char *git_dir = hs_join_path(g->repo_path, ".git");
    int exists = hs_dir_exists(git_dir);
    free(git_dir);
    return exists;
}

void hs_git_snapshot(hs_git *g, const hs_groupvec *groups) {
    update_gitignore(g, groups);

    for (size_t i = 0; i < groups->len; i++) {
        const hs_sync_group *grp = &groups->data[i];
        for (size_t j = 0; j < grp->paths.len; j++) {
            char *expanded = hs_expand_path(grp->paths.data[j]);
            if (hs_file_exists(expanded) || hs_dir_exists(expanded)) {
                copy_to_repo(g, expanded);
            } else {
                hs_debug("skipping non-existent path: %s", expanded);
            }
            free(expanded);
        }
    }

    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("add"));
    hs_vec_push(&args, strdup("-A"));
    hs_exec_result r = git_exec(g, &args);
    hs_strvec_free(&args);
    hs_exec_result_free(&r);
}

void hs_git_snapshot_changed(hs_git *g, const hs_strvec *changed_paths,
                             const hs_groupvec *groups) {
    update_gitignore(g, groups);

    for (size_t c = 0; c < changed_paths->len; c++) {
        const char *changed = changed_paths->data[c];
        int tracked = 0;

        for (size_t i = 0; i < groups->len && !tracked; i++) {
            const hs_sync_group *grp = &groups->data[i];
            for (size_t j = 0; j < grp->paths.len; j++) {
                char *expanded = hs_expand_path(grp->paths.data[j]);
                if (strncmp(changed, expanded, strlen(expanded)) == 0) {
                    tracked = 1;
                    free(expanded);
                    break;
                }
                free(expanded);
            }
        }

        if (tracked && (hs_file_exists(changed) || hs_dir_exists(changed)))
            copy_to_repo(g, changed);
    }

    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("add"));
    hs_vec_push(&args, strdup("-A"));
    hs_exec_result r = git_exec(g, &args);
    hs_strvec_free(&args);
    hs_exec_result_free(&r);
}

void hs_git_restore(hs_git *g, const hs_groupvec *groups) {
    for (size_t i = 0; i < groups->len; i++) {
        const hs_sync_group *grp = &groups->data[i];
        for (size_t j = 0; j < grp->paths.len; j++) {
            char *expanded = hs_expand_path(grp->paths.data[j]);
            char *repo_rel = hs_git_to_repo_path(g, expanded);
            char *repo_file = hs_join_path(g->repo_path, repo_rel);

            if (hs_file_exists(repo_file) || hs_dir_exists(repo_file))
                copy_from_repo(g, repo_file);

            free(expanded);
            free(repo_rel);
            free(repo_file);
        }
    }
}

int hs_git_commit(hs_git *g, const char *message) {
    if (!hs_git_has_changes(g)) {
        hs_debug("no changes to commit");
        return 1;
    }

    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("commit"));
    hs_vec_push(&args, strdup("-m"));
    hs_vec_push(&args, strdup(message));
    hs_exec_result result = git_exec(g, &args);
    hs_strvec_free(&args);

    if (!hs_exec_success(&result)) {
        hs_error("commit failed: %s", result.stderr_output);
        hs_exec_result_free(&result);
        return 0;
    }

    hs_exec_result_free(&result);
    hs_info("committed: %s", message);
    return 1;
}

int hs_git_has_changes(const hs_git *g) {
    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("status"));
    hs_vec_push(&args, strdup("--porcelain"));
    hs_exec_result result = git_exec(g, &args);
    hs_strvec_free(&args);

    int has = 0;
    if (hs_exec_success(&result)) {
        char *trimmed = hs_trim(result.stdout_output);
        has = (trimmed && trimmed[0] != '\0');
        free(trimmed);
    }
    hs_exec_result_free(&result);
    return has;
}

char *hs_git_diff(const hs_git *g) {
    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("diff"));
    hs_exec_result result = git_exec(g, &args);
    hs_strvec_free(&args);
    char *out = result.stdout_output;
    result.stdout_output = NULL;
    hs_exec_result_free(&result);
    return out;
}

char *hs_git_diff_staged(const hs_git *g) {
    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("diff"));
    hs_vec_push(&args, strdup("--cached"));
    hs_exec_result result = git_exec(g, &args);
    hs_strvec_free(&args);
    char *out = result.stdout_output;
    result.stdout_output = NULL;
    hs_exec_result_free(&result);
    return out;
}

char *hs_git_diff_remote(const hs_git *g, const char *device) {
    size_t blen = strlen("remote/") + strlen(device) + 1;
    char *branch = malloc(blen);
    snprintf(branch, blen, "remote/%s", device);

    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("diff"));
    hs_vec_push(&args, branch);
    hs_exec_result result = git_exec(g, &args);
    hs_strvec_free(&args);
    char *out = result.stdout_output;
    result.stdout_output = NULL;
    hs_exec_result_free(&result);
    return out;
}

hs_strvec hs_git_log(const hs_git *g, int count) {
    hs_strvec entries;
    hs_vec_init(&entries);

    char countbuf[32];
    snprintf(countbuf, sizeof(countbuf), "%d", count);

    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("log"));
    hs_vec_push(&args, strdup("--oneline"));
    hs_vec_push(&args, strdup("-n"));
    hs_vec_push(&args, strdup(countbuf));
    hs_exec_result result = git_exec(g, &args);
    hs_strvec_free(&args);

    if (hs_exec_success(&result)) {
        char *text = result.stdout_output;
        char *saveptr = NULL;
        char *line = strtok_r(text, "\n", &saveptr);
        while (line) {
            if (line[0] != '\0')
                hs_vec_push(&entries, strdup(line));
            line = strtok_r(NULL, "\n", &saveptr);
        }
    }
    hs_exec_result_free(&result);
    return entries;
}

hs_strvec hs_git_changed_files(const hs_git *g) {
    hs_strvec files;
    hs_vec_init(&files);

    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("status"));
    hs_vec_push(&args, strdup("--porcelain"));
    hs_exec_result result = git_exec(g, &args);
    hs_strvec_free(&args);

    if (hs_exec_success(&result)) {
        char *text = result.stdout_output;
        char *saveptr = NULL;
        char *line = strtok_r(text, "\n", &saveptr);
        while (line) {
            if (strlen(line) > 3)
                hs_vec_push(&files, strdup(line + 3));
            line = strtok_r(NULL, "\n", &saveptr);
        }
    }
    hs_exec_result_free(&result);
    return files;
}

hs_conflictvec hs_git_get_conflicts(const hs_git *g) {
    hs_conflictvec conflicts;
    hs_vec_init(&conflicts);

    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("diff"));
    hs_vec_push(&args, strdup("--name-only"));
    hs_vec_push(&args, strdup("--diff-filter=U"));
    hs_exec_result result = git_exec(g, &args);
    hs_strvec_free(&args);

    if (hs_exec_success(&result)) {
        char *text = result.stdout_output;
        char *saveptr = NULL;
        char *line = strtok_r(text, "\n", &saveptr);
        while (line) {
            if (line[0] != '\0') {
                hs_conflict_file cf;
                cf.path = strdup(line);
                cf.ours = NULL;
                cf.theirs = NULL;
                hs_vec_push(&conflicts, cf);
            }
            line = strtok_r(NULL, "\n", &saveptr);
        }
    }
    hs_exec_result_free(&result);
    return conflicts;
}

static time_t file_mtime(const char *path) {
    struct stat st;
    if (stat(path, &st) != 0) return 0;
    return st.st_mtime;
}

int hs_git_resolve_conflict(hs_git *g, const char *file,
                            hs_conflict_strategy strategy) {
    hs_exec_result result;
    memset(&result, 0, sizeof(result));

    hs_strvec args;

    switch (strategy) {
    case HS_CONFLICT_NEWEST_WINS: {
        char *repo_file = hs_join_path(g->repo_path, file);
        char *original = hs_git_to_original_path(g, file);

        if (hs_file_exists(repo_file) && hs_file_exists(original)) {
            time_t repo_time = file_mtime(repo_file);
            time_t orig_time = file_mtime(original);

            hs_vec_init(&args);
            hs_vec_push(&args, strdup("checkout"));
            if (orig_time > repo_time)
                hs_vec_push(&args, strdup("--ours"));
            else
                hs_vec_push(&args, strdup("--theirs"));
            hs_vec_push(&args, strdup(file));
            result = git_exec(g, &args);
            hs_strvec_free(&args);
        } else {
            hs_vec_init(&args);
            hs_vec_push(&args, strdup("checkout"));
            hs_vec_push(&args, strdup("--theirs"));
            hs_vec_push(&args, strdup(file));
            result = git_exec(g, &args);
            hs_strvec_free(&args);
        }

        free(repo_file);
        free(original);
        break;
    }

    case HS_CONFLICT_KEEP_BOTH: {
        char *repo_file = hs_join_path(g->repo_path, file);

        size_t ours_len = strlen(repo_file) + 1 + strlen(g->hostname) + 1;
        char *ours_file = malloc(ours_len);
        snprintf(ours_file, ours_len, "%s.%s", repo_file, g->hostname);

        size_t theirs_len = strlen(repo_file) + strlen(".remote") + 1;
        char *theirs_file = malloc(theirs_len);
        snprintf(theirs_file, theirs_len, "%s.remote", repo_file);

        size_t show_arg_len = 3 + strlen(file) + 1;
        char *show_ours_arg = malloc(show_arg_len);
        snprintf(show_ours_arg, show_arg_len, ":2:%s", file);

        hs_vec_init(&args);
        hs_vec_push(&args, strdup("show"));
        hs_vec_push(&args, show_ours_arg);
        hs_exec_result ours_result = git_exec(g, &args);
        hs_strvec_free(&args);

        if (hs_exec_success(&ours_result)) {
            FILE *f = fopen(ours_file, "w");
            if (f) {
                fputs(ours_result.stdout_output, f);
                fclose(f);
                hs_info("saved local version as: %s", ours_file);
            }
        }
        hs_exec_result_free(&ours_result);

        char *show_theirs_arg = malloc(show_arg_len);
        snprintf(show_theirs_arg, show_arg_len, ":3:%s", file);

        hs_vec_init(&args);
        hs_vec_push(&args, strdup("show"));
        hs_vec_push(&args, show_theirs_arg);
        hs_exec_result theirs_result = git_exec(g, &args);
        hs_strvec_free(&args);

        if (hs_exec_success(&theirs_result)) {
            FILE *f = fopen(theirs_file, "w");
            if (f) {
                fputs(theirs_result.stdout_output, f);
                fclose(f);
                hs_info("saved remote version as: %s", theirs_file);
            }
        }
        hs_exec_result_free(&theirs_result);

        hs_vec_init(&args);
        hs_vec_push(&args, strdup("checkout"));
        hs_vec_push(&args, strdup("--theirs"));
        hs_vec_push(&args, strdup(file));
        result = git_exec(g, &args);
        hs_strvec_free(&args);

        free(repo_file);
        free(ours_file);
        free(theirs_file);
        break;
    }

    case HS_CONFLICT_MANUAL:
    default:
        hs_info("manual resolution required for: %s", file);
        return 0;
    }

    if (hs_exec_success(&result)) {
        hs_exec_result_free(&result);
        hs_vec_init(&args);
        hs_vec_push(&args, strdup("add"));
        hs_vec_push(&args, strdup(file));
        hs_exec_result add_result = git_exec(g, &args);
        hs_strvec_free(&args);
        hs_exec_result_free(&add_result);
        return 1;
    }

    hs_exec_result_free(&result);
    return 0;
}

int hs_git_has_conflicts(const hs_git *g) {
    hs_conflictvec conflicts = hs_git_get_conflicts(g);
    int has = (conflicts.len > 0);
    hs_conflictvec_free(&conflicts);
    return has;
}

void hs_git_create_device_branch(hs_git *g, const char *device) {
    size_t blen = strlen("remote/") + strlen(device) + 1;
    char *branch = malloc(blen);
    snprintf(branch, blen, "remote/%s", device);

    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("branch"));
    hs_vec_push(&args, branch);
    hs_exec_result r = git_exec(g, &args);
    hs_strvec_free(&args);
    hs_exec_result_free(&r);
}

void hs_git_update_device_branch(hs_git *g, const char *device) {
    size_t blen = strlen("remote/") + strlen(device) + 1;
    char *branch = malloc(blen);
    snprintf(branch, blen, "remote/%s", device);

    hs_strvec args;
    hs_vec_init(&args);
    hs_vec_push(&args, strdup("branch"));
    hs_vec_push(&args, strdup("-f"));
    hs_vec_push(&args, branch);
    hs_vec_push(&args, strdup("HEAD"));
    hs_exec_result r = git_exec(g, &args);
    hs_strvec_free(&args);
    hs_exec_result_free(&r);
}

char *hs_git_to_repo_path(const hs_git *g, const char *original) {
    char *expanded = hs_expand_path(original);
    if (!expanded) return strdup(original);

    size_t home_len = strlen(g->home_dir);
    if (strncmp(expanded, g->home_dir, home_len) == 0) {
        const char *rel = expanded + home_len;
        if (*rel == '/') rel++;
        char *result = strdup(rel);
        free(expanded);
        return result;
    }

    return expanded;
}

char *hs_git_to_original_path(const hs_git *g, const char *repo_relative) {
    return hs_join_path(g->home_dir, repo_relative);
}

void hs_conflict_file_free(hs_conflict_file *f) {
    if (!f) return;
    free(f->path);
    free(f->ours);
    free(f->theirs);
}

void hs_conflictvec_free(hs_conflictvec *v) {
    if (!v) return;
    for (size_t i = 0; i < v->len; i++)
        hs_conflict_file_free(&v->data[i]);
    hs_vec_free(v);
}
